// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://auzdjwpkhobgzvmwnzie.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImF1emRqd3BraG9iZ3p2bXduemllIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE4NTY3OTcsImV4cCI6MjA2NzQzMjc5N30.I7vdqH7dkl8YJOD_Zfos2ZrZHTpfhy6nDKRFJDqmINs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});